<?php

namespace EP;
const LINES_ADDED = "LINES_ADDED";
const AVG_PASTE = "AVG_PASTE";
const AVG_TEST = "AVG_TEST";
const COMPILED_FAILS = "COMPILED_FAILS";
const COMPILED_SUCCESS = "COMPILED_SUCCESS";
const LINES_DELETED = "LINES_DELETED";
const MAX_PASTE_LEN = "MAX_PASTE_LEN";
const LINES_MODIFIED = "LINES_MODIFIED";
const NUM_PASTES = "NUM_PASTES";
const TS_SPEED = "TS_SPEED";
const TESTINGS = "TESTINGS";
const WORK_TIME = "WORK_TIME";
const SHORT_BREAKS = "SHORT_BREAKS";
const LONG_BREAKS = "LONG_BREAKS";
const TIME_FROM_DEADLINE = "TIME_FROM_DEADLINE";


const ALL_NUMBERS = "ALL_NUMBERS";
const NUM_ARRAYS = "NUM_ARRAYS";
const AVG_LINE_LEN = "AVG_LINE_LEN";
const NUM_BLOCKS = "NUM_BLOCKS";
const NUM_BRANCHES = "NUM_BRANCHES";
const NUM_CHARS = "NUM_CHARS";
const COMP_OP = "COMP_OP";
const NUM_FUN = "NUM_FUN";
const NUM_INCLUDE = "NUM_INCLUDE";
const NUM_ARRAY_ACCESS = "NUM_ARRAY_ACCESS";
const NUM_LITERALS = "NUM_LITERALS";
const LOC = "LOC";
const NUM_LOOPS = "NUM_LOOPS";
const MAIN_LEN = "MAIN_LEN";
const NUM_MLCOMMENTS = "NUM_MLCOMMENTS";
const NUM_MODULO_INCDEC_OP = "NUM_MODULO_INCDEC_OP";
const MULDIV_OP = "MULDIV_OP";
const NEG_OP = "NEG_OP";
const NUM_BRACES = "NUM_BRACES";
const NUM_COMMAS = "NUM_COMMAS";
const PLUSMINUS_OP = "PLUSMINUS_OP";
const RARE_OP = "RARE_OP";
const EQUAL_OP = "EQUAL_OP";
const NUM_SLCOMMENTS = "NUM_SLCOMMENTS";
const SLOC = "SLOC";
const SLOC_CMD = "SLOC_CMD";
const ORAND_OP = "ORAND_OP";
const NUM_STRING = "NUM_STRING";
const NUM_TRYS = "NUM_TRYS";
const NUM_VARS = "NUM_VARS";
const NUM_WORDS = "NUM_WORDS";
const NUMBERS = "NUMBERS";


const DEFAULT_DISTANCE = 1;
const DEFAULT_THRESHOLD = 0.15;
const SOURCES_PATH = "src";
const STATS_PATH = "/home/vedran/Code/cloud9/stats/OR2016";
const GA_POPULATION_SIZE = 50;
const GA_PROGENITORS_SIZE = 10;
const GA_MUTATION_PROBABILITY = 0.2; // 0.02
const GENOME_SIZE = 47;
const NR_DYNAMIC_FEATURES = 15;
const RECONSTRUCT_USE_GOTO = true;
const SKIP_DYNAMIC = false; // Ignore dynamic features, just use static


?>
